[2024-05-21T19:10:28.346+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T19:10:28.358+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [queued]>
[2024-05-21T19:10:28.363+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [queued]>
[2024-05-21T19:10:28.363+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T19:10:28.371+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-05-21 19:10:17.300923+00:00
[2024-05-21T19:10:28.375+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1503) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T19:10:28.376+0000] {standard_task_runner.py:63} INFO - Started process 1504 to run task
[2024-05-21T19:10:28.376+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'send_to_kafka', 'manual__2024-05-21T19:10:17.300923+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmp615e9u_x']
[2024-05-21T19:10:28.377+0000] {standard_task_runner.py:91} INFO - Job 343: Subtask send_to_kafka
[2024-05-21T19:10:28.401+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [running]> on host cef94752cfd3
[2024-05-21T19:10:28.448+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T19:10:17.300923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T19:10:17.300923+00:00'
[2024-05-21T19:10:28.449+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T19:10:28.459+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T19:10:28.459+0000] {minio.py:100} INFO - Start reading unprocessed data
[2024-05-21T19:10:28.459+0000] {minio.py:126} INFO - Start reading data from object name processed_files
[2024-05-21T19:10:28.483+0000] {minio.py:113} INFO - Object response2024_05_21_p_1.json was already processed, skipping ...
[2024-05-21T19:10:28.484+0000] {minio.py:113} INFO - Object response2024_05_21_p_2.json was already processed, skipping ...
[2024-05-21T19:10:28.484+0000] {minio.py:113} INFO - Object response2024_05_21_p_3.json was already processed, skipping ...
[2024-05-21T19:10:28.484+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T19:10:28.485+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T19:10:28.489+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=send_to_kafka, execution_date=20240521T191017, start_date=20240521T191028, end_date=20240521T191028
[2024-05-21T19:10:28.508+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T19:10:28.517+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T19:10:28.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
