[2024-05-21T19:12:53.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T19:12:53.326+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [queued]>
[2024-05-21T19:12:53.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [queued]>
[2024-05-21T19:12:53.331+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-21T19:12:53.340+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-05-21 19:10:17.300923+00:00
[2024-05-21T19:12:53.343+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2032) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T19:12:53.344+0000] {standard_task_runner.py:63} INFO - Started process 2033 to run task
[2024-05-21T19:12:53.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'send_to_kafka', 'manual__2024-05-21T19:10:17.300923+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmpa5s3ajkx']
[2024-05-21T19:12:53.345+0000] {standard_task_runner.py:91} INFO - Job 347: Subtask send_to_kafka
[2024-05-21T19:12:53.366+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T19:10:17.300923+00:00 [running]> on host cef94752cfd3
[2024-05-21T19:12:53.410+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T19:10:17.300923+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T19:10:17.300923+00:00'
[2024-05-21T19:12:53.411+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T19:12:53.420+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T19:12:53.420+0000] {minio.py:100} INFO - Start reading unprocessed data
[2024-05-21T19:12:53.421+0000] {minio.py:126} INFO - Start reading data from object name processed_files
[2024-05-21T19:12:53.450+0000] {minio.py:113} INFO - Object response2024_05_21_p_1.json was already processed, skipping ...
[2024-05-21T19:12:53.450+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_2.json
[2024-05-21T19:12:53.471+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_3.json
[2024-05-21T19:13:18.579+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-05-21T19:13:18.580+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-21T19:13:18.581+0000] {process_utils.py:132} INFO - Sending 15 to group 2033. PIDs of all processes in the group: [2033]
[2024-05-21T19:13:18.582+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2033
[2024-05-21T19:13:18.583+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-21T19:13:18.584+0000] {kafka.py:59} WARNING - Error occured while sending data to kafka. Object name response2024_05_21_p_2.json
[2024-05-21T19:13:58.655+0000] {minio.py:148} INFO - Start writing data to file name processed_files
[2024-05-21T19:13:58.727+0000] {minio.py:180} INFO - Successfully save filename to object: processed_files.
[2024-05-21T19:13:58.728+0000] {kafka.py:57} INFO - Data was successfully send. Object name response2024_05_21_p_3.json
[2024-05-21T19:13:58.728+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T19:13:58.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T19:13:58.734+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=send_to_kafka, execution_date=20240521T191017, start_date=20240521T191253, end_date=20240521T191358
[2024-05-21T19:13:58.755+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2033, status='terminated', exitcode=0, started='19:12:53') (2033) terminated with exit code 0
