[2024-05-21T18:56:01.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T18:56:01.260+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T18:56:01.265+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T18:56:01.266+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 7
[2024-05-21T18:56:01.274+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-05-21 16:04:29.980796+00:00
[2024-05-21T18:56:01.277+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1048) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T18:56:01.278+0000] {standard_task_runner.py:63} INFO - Started process 1049 to run task
[2024-05-21T18:56:01.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'send_to_kafka', 'manual__2024-05-21T16:04:29.980796+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmpzvgnydpm']
[2024-05-21T18:56:01.280+0000] {standard_task_runner.py:91} INFO - Job 330: Subtask send_to_kafka
[2024-05-21T18:56:01.304+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [running]> on host 0bedcfb13132
[2024-05-21T18:56:01.349+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T16:04:29.980796+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T16:04:29.980796+00:00'
[2024-05-21T18:56:01.350+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T18:56:01.359+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T18:56:01.360+0000] {minio.py:100} INFO - Start reading unprocessed data
[2024-05-21T18:56:01.360+0000] {minio.py:126} INFO - Start reading data from object name processed_files
[2024-05-21T18:56:01.394+0000] {minio.py:113} INFO - Object response2024_05_21_p_1.json was already processed, skipping ...
[2024-05-21T18:56:01.394+0000] {minio.py:113} INFO - Object response2024_05_21_p_2.json was already processed, skipping ...
[2024-05-21T18:56:01.394+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_3.json
[2024-05-21T18:56:42.409+0000] {minio.py:148} INFO - Start writing data to file name processed_files
[2024-05-21T18:56:42.442+0000] {minio.py:180} INFO - Successfully save filename to object: processed_files.
[2024-05-21T18:56:42.442+0000] {kafka.py:57} INFO - Data was successfully send. Object name response2024_05_21_p_3.json
[2024-05-21T18:56:42.443+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T18:56:42.443+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T18:56:42.449+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=send_to_kafka, execution_date=20240521T160429, start_date=20240521T185601, end_date=20240521T185642
[2024-05-21T18:56:42.493+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T18:56:42.502+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T18:56:42.503+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
