[2024-05-21T19:04:19.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T19:04:20.000+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T19:04:20.005+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T19:04:20.005+0000] {taskinstance.py:2303} INFO - Starting attempt 9 of 9
[2024-05-21T19:04:20.014+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): pull_and_save_from_api> on 2024-05-21 16:04:29.980796+00:00
[2024-05-21T19:04:20.017+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T19:04:20.018+0000] {standard_task_runner.py:63} INFO - Started process 503 to run task
[2024-05-21T19:04:20.018+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'pull_and_save_from_api', 'manual__2024-05-21T16:04:29.980796+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmp9fpt8lzs']
[2024-05-21T19:04:20.019+0000] {standard_task_runner.py:91} INFO - Job 334: Subtask pull_and_save_from_api
[2024-05-21T19:04:20.041+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T16:04:29.980796+00:00 [running]> on host cef94752cfd3
[2024-05-21T19:04:20.084+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='pull_and_save_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T16:04:29.980796+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T16:04:29.980796+00:00'
[2024-05-21T19:04:20.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T19:04:20.214+0000] {pull.py:50} INFO - Token acquired successfully.
[2024-05-21T19:04:20.216+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T19:04:20.221+0000] {minio.py:126} INFO - Start reading data from object name last_pull
[2024-05-21T19:04:20.244+0000] {minio.py:14} INFO - Last pull occured less than 1 day ago. No pull needed
[2024-05-21T19:04:20.245+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T19:04:20.245+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T19:04:20.250+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=pull_and_save_from_api, execution_date=20240521T160429, start_date=20240521T190420, end_date=20240521T190420
[2024-05-21T19:04:20.271+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T19:04:20.281+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-21T19:04:20.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
